2025-05-21 13:19:23,297 - ERROR - Failed to get langauge of the text: 
Traceback (most recent call last):
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\utils.py", line 25, in detect_language
    return detect(text)
           ^^^^^^^^^^^^
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\env\Lib\site-packages\langdetect\detector_factory.py", line 130, in detect
    return detector.detect()
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\env\Lib\site-packages\langdetect\detector.py", line 136, in detect
    probabilities = self.get_probabilities()
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\env\Lib\site-packages\langdetect\detector.py", line 143, in get_probabilities
    self._detect_block()
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\env\Lib\site-packages\langdetect\detector.py", line 150, in _detect_block
    raise LangDetectException(ErrorCode.CantDetectError, 'No features in text.')
langdetect.lang_detect_exception.LangDetectException: No features in text.
2025-05-21 13:19:23,312 - ERROR - Failed to get langauge of the text: 
Traceback (most recent call last):
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\utils.py", line 25, in detect_language
    return detect(text)
           ^^^^^^^^^^^^
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\env\Lib\site-packages\langdetect\detector_factory.py", line 130, in detect
    return detector.detect()
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\env\Lib\site-packages\langdetect\detector.py", line 136, in detect
    probabilities = self.get_probabilities()
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\env\Lib\site-packages\langdetect\detector.py", line 143, in get_probabilities
    self._detect_block()
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\env\Lib\site-packages\langdetect\detector.py", line 150, in _detect_block
    raise LangDetectException(ErrorCode.CantDetectError, 'No features in text.')
langdetect.lang_detect_exception.LangDetectException: No features in text.
2025-05-21 13:19:23,315 - ERROR - Failed to get langauge of the text: 
Traceback (most recent call last):
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\utils.py", line 25, in detect_language
    return detect(text)
           ^^^^^^^^^^^^
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\env\Lib\site-packages\langdetect\detector_factory.py", line 130, in detect
    return detector.detect()
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\env\Lib\site-packages\langdetect\detector.py", line 136, in detect
    probabilities = self.get_probabilities()
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\env\Lib\site-packages\langdetect\detector.py", line 143, in get_probabilities
    self._detect_block()
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\env\Lib\site-packages\langdetect\detector.py", line 150, in _detect_block
    raise LangDetectException(ErrorCode.CantDetectError, 'No features in text.')
langdetect.lang_detect_exception.LangDetectException: No features in text.
2025-05-21 13:19:23,315 - ERROR - Failed to get langauge of the text: 
Traceback (most recent call last):
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\utils.py", line 25, in detect_language
    return detect(text)
           ^^^^^^^^^^^^
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\env\Lib\site-packages\langdetect\detector_factory.py", line 130, in detect
    return detector.detect()
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\env\Lib\site-packages\langdetect\detector.py", line 136, in detect
    probabilities = self.get_probabilities()
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\env\Lib\site-packages\langdetect\detector.py", line 143, in get_probabilities
    self._detect_block()
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\env\Lib\site-packages\langdetect\detector.py", line 150, in _detect_block
    raise LangDetectException(ErrorCode.CantDetectError, 'No features in text.')
langdetect.lang_detect_exception.LangDetectException: No features in text.
2025-05-21 13:19:23,332 - ERROR - Failed to get langauge of the text: 
Traceback (most recent call last):
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\utils.py", line 25, in detect_language
    return detect(text)
           ^^^^^^^^^^^^
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\env\Lib\site-packages\langdetect\detector_factory.py", line 130, in detect
    return detector.detect()
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\env\Lib\site-packages\langdetect\detector.py", line 136, in detect
    probabilities = self.get_probabilities()
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\env\Lib\site-packages\langdetect\detector.py", line 143, in get_probabilities
    self._detect_block()
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\env\Lib\site-packages\langdetect\detector.py", line 150, in _detect_block
    raise LangDetectException(ErrorCode.CantDetectError, 'No features in text.')
langdetect.lang_detect_exception.LangDetectException: No features in text.
2025-05-21 13:19:23,393 - ERROR - Failed to get langauge of the text: 
Traceback (most recent call last):
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\utils.py", line 25, in detect_language
    return detect(text)
           ^^^^^^^^^^^^
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\env\Lib\site-packages\langdetect\detector_factory.py", line 130, in detect
    return detector.detect()
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\env\Lib\site-packages\langdetect\detector.py", line 136, in detect
    probabilities = self.get_probabilities()
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\env\Lib\site-packages\langdetect\detector.py", line 143, in get_probabilities
    self._detect_block()
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\env\Lib\site-packages\langdetect\detector.py", line 150, in _detect_block
    raise LangDetectException(ErrorCode.CantDetectError, 'No features in text.')
langdetect.lang_detect_exception.LangDetectException: No features in text.
2025-05-21 13:19:24,469 - ERROR - Failed to get langauge of the text: 
Traceback (most recent call last):
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\utils.py", line 25, in detect_language
    return detect(text)
           ^^^^^^^^^^^^
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\env\Lib\site-packages\langdetect\detector_factory.py", line 130, in detect
    return detector.detect()
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\env\Lib\site-packages\langdetect\detector.py", line 136, in detect
    probabilities = self.get_probabilities()
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\env\Lib\site-packages\langdetect\detector.py", line 143, in get_probabilities
    self._detect_block()
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\env\Lib\site-packages\langdetect\detector.py", line 150, in _detect_block
    raise LangDetectException(ErrorCode.CantDetectError, 'No features in text.')
langdetect.lang_detect_exception.LangDetectException: No features in text.
2025-05-21 13:19:24,946 - ERROR - Failed to get langauge of the text: 
Traceback (most recent call last):
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\utils.py", line 25, in detect_language
    return detect(text)
           ^^^^^^^^^^^^
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\env\Lib\site-packages\langdetect\detector_factory.py", line 130, in detect
    return detector.detect()
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\env\Lib\site-packages\langdetect\detector.py", line 136, in detect
    probabilities = self.get_probabilities()
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\env\Lib\site-packages\langdetect\detector.py", line 143, in get_probabilities
    self._detect_block()
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\env\Lib\site-packages\langdetect\detector.py", line 150, in _detect_block
    raise LangDetectException(ErrorCode.CantDetectError, 'No features in text.')
langdetect.lang_detect_exception.LangDetectException: No features in text.
2025-05-21 13:19:24,997 - ERROR - Failed to get langauge of the text: 
Traceback (most recent call last):
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\utils.py", line 25, in detect_language
    return detect(text)
           ^^^^^^^^^^^^
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\env\Lib\site-packages\langdetect\detector_factory.py", line 130, in detect
    return detector.detect()
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\env\Lib\site-packages\langdetect\detector.py", line 136, in detect
    probabilities = self.get_probabilities()
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\env\Lib\site-packages\langdetect\detector.py", line 143, in get_probabilities
    self._detect_block()
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\env\Lib\site-packages\langdetect\detector.py", line 150, in _detect_block
    raise LangDetectException(ErrorCode.CantDetectError, 'No features in text.')
langdetect.lang_detect_exception.LangDetectException: No features in text.
2025-05-21 13:19:25,047 - ERROR - Failed to get langauge of the text: 
Traceback (most recent call last):
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\utils.py", line 25, in detect_language
    return detect(text)
           ^^^^^^^^^^^^
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\env\Lib\site-packages\langdetect\detector_factory.py", line 130, in detect
    return detector.detect()
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\env\Lib\site-packages\langdetect\detector.py", line 136, in detect
    probabilities = self.get_probabilities()
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\env\Lib\site-packages\langdetect\detector.py", line 143, in get_probabilities
    self._detect_block()
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\env\Lib\site-packages\langdetect\detector.py", line 150, in _detect_block
    raise LangDetectException(ErrorCode.CantDetectError, 'No features in text.')
langdetect.lang_detect_exception.LangDetectException: No features in text.
2025-05-21 13:19:30,852 - ERROR - Failed to get langauge of the text: 
Traceback (most recent call last):
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\utils.py", line 25, in detect_language
    return detect(text)
           ^^^^^^^^^^^^
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\env\Lib\site-packages\langdetect\detector_factory.py", line 130, in detect
    return detector.detect()
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\env\Lib\site-packages\langdetect\detector.py", line 136, in detect
    probabilities = self.get_probabilities()
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\env\Lib\site-packages\langdetect\detector.py", line 143, in get_probabilities
    self._detect_block()
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\env\Lib\site-packages\langdetect\detector.py", line 150, in _detect_block
    raise LangDetectException(ErrorCode.CantDetectError, 'No features in text.')
langdetect.lang_detect_exception.LangDetectException: No features in text.
2025-05-21 13:20:35,930 - ERROR - Failed to access feed https://www.cbc.ca/webfeed/rss/rss-topstories after retries, skipping...
2025-05-21 13:20:38,126 - ERROR - Failed to get langauge of the text: 
Traceback (most recent call last):
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\utils.py", line 25, in detect_language
    return detect(text)
           ^^^^^^^^^^^^
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\env\Lib\site-packages\langdetect\detector_factory.py", line 130, in detect
    return detector.detect()
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\env\Lib\site-packages\langdetect\detector.py", line 136, in detect
    probabilities = self.get_probabilities()
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\env\Lib\site-packages\langdetect\detector.py", line 143, in get_probabilities
    self._detect_block()
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\env\Lib\site-packages\langdetect\detector.py", line 150, in _detect_block
    raise LangDetectException(ErrorCode.CantDetectError, 'No features in text.')
langdetect.lang_detect_exception.LangDetectException: No features in text.
2025-05-21 13:20:38,191 - ERROR - Failed to get langauge of the text: 
Traceback (most recent call last):
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\utils.py", line 25, in detect_language
    return detect(text)
           ^^^^^^^^^^^^
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\env\Lib\site-packages\langdetect\detector_factory.py", line 130, in detect
    return detector.detect()
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\env\Lib\site-packages\langdetect\detector.py", line 136, in detect
    probabilities = self.get_probabilities()
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\env\Lib\site-packages\langdetect\detector.py", line 143, in get_probabilities
    self._detect_block()
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\env\Lib\site-packages\langdetect\detector.py", line 150, in _detect_block
    raise LangDetectException(ErrorCode.CantDetectError, 'No features in text.')
langdetect.lang_detect_exception.LangDetectException: No features in text.
2025-05-21 13:20:43,340 - ERROR - Failed to get langauge of the text: 
Traceback (most recent call last):
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\utils.py", line 25, in detect_language
    return detect(text)
           ^^^^^^^^^^^^
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\env\Lib\site-packages\langdetect\detector_factory.py", line 130, in detect
    return detector.detect()
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\env\Lib\site-packages\langdetect\detector.py", line 136, in detect
    probabilities = self.get_probabilities()
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\env\Lib\site-packages\langdetect\detector.py", line 143, in get_probabilities
    self._detect_block()
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\env\Lib\site-packages\langdetect\detector.py", line 150, in _detect_block
    raise LangDetectException(ErrorCode.CantDetectError, 'No features in text.')
langdetect.lang_detect_exception.LangDetectException: No features in text.
2025-05-21 13:20:43,361 - ERROR - Failed to get langauge of the text: 
Traceback (most recent call last):
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\utils.py", line 25, in detect_language
    return detect(text)
           ^^^^^^^^^^^^
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\env\Lib\site-packages\langdetect\detector_factory.py", line 130, in detect
    return detector.detect()
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\env\Lib\site-packages\langdetect\detector.py", line 136, in detect
    probabilities = self.get_probabilities()
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\env\Lib\site-packages\langdetect\detector.py", line 143, in get_probabilities
    self._detect_block()
  File "C:\Users\SHADO\OneDrive\Desktop\rss_aggregator\env\Lib\site-packages\langdetect\detector.py", line 150, in _detect_block
    raise LangDetectException(ErrorCode.CantDetectError, 'No features in text.')
langdetect.lang_detect_exception.LangDetectException: No features in text.
